import { Event } from "../events.js";

export const AGEOFASHES = [
    new Event("aoa","Call to Heroes",4719,9,22),
    new Event("aoa","Met Benjemyn Trayle; discovered Alseta's Ring",4719,9,24),
    new Event("ec","The Circus of Wayward Wonders performs in Abberton; the Ringmaster is murdered",4720,2,5),
    new Event("aoa","Travelled through Huntergate; Met the Ekujae",4719,10,15),
    new Event("aoa","Attended the Akrivel Welcome Feast",4719,10,16),
    new Event("aoa","Met Gerhard Pendergrast",4719,10,26),
    new Event("aoa","Ancient Temple exploded; Gerhard Pendergrast died",4719,10,29),
    new Event("aoa","Cleared out the Cinderclaw Mine; Ben slept outside and got malaria",4719,11,11),
    new Event("aoa","Defeated Belmazog at the Fortress of Sorrow; Met the red dragon, Kyrion",4719,11,22),
    new Event("aoa","Destroyed the Vision of Dahak; Returned to Breachill",4719,12,1),
    new Event("aoa","Dr Bang was kidnapped by the Scarlet Triad",4719,12,8),
    new Event("aoa","Travelled through Dreamgate",4719,12,9),
    new Event("aoa","Stopped slavers at Cypress Point; Grannok was humbled",4719,12,10),
    new Event("aoa","Assaulted Summershade Granite Quarry; Ben was blinded by a lich",4719,12,14),
    new Event("aoa","Halleka restored Ben's sight; Laslunn was defeated",4719,12,17),
    new Event("aoa","Travelled through Jewelgate",4720,1,2),
    new Event("aoa","Met Kovlar's Council of Regents",4720,1,3),
    new Event("aoa","Grannok (and then the others) were arrested by Chiselrock's corrupt guards",4720,1,4),
    new Event("aoa","Freed Triad slaves from the Hidden Forge; Met with King Harral",4720,1,6),
    new Event("aoa","Defeated Ilssrah Embermead",4720,1,9),
    new Event("aoa","Defeated Veshumirix; Returned King Harral's crown",4720,1,10),
    new Event("aoa","Travelled through Duskgate",4720,1,16),
    new Event("aoa","Arrived in Katapesh; Began planning how to discredit Uri and the Scarlet Triad",4720,1,21),
    new Event("aoa","Grannok became the leader of the Katapesh Gladiator Guild",4720,2,12),
    new Event("aoa","Exavisu Kerndallion and other slaves were rescued from the Bhetshamtal Estate",4720,2,14),
    new Event("aoa","Lord Bossleworth was declared dead; Uri and the Scarlet Triad were discredited from the Council of Guilds",4720,2,26),
    new Event("aoa","Uri Zandivar was defeated",4720,2,27),
    new Event("aoa","Attempted to open Vengegate; The Manifestation of Dahak attacked Breachill",4720,4,4),
    new Event("aoa","Arrived in Hermea; Met Emaliza and Inizra",4720,4,5),
    new Event("aoa","Dr Bang was ordered by Emaliza to obtain the Shards of Gold Dragonkind",4720,4,6),
    new Event("aoa","Fought Emaliza alongside Mengkare; Convinced the gold dragon to try the altered version of the anima invocation",4720,4,8),
    new Event("aoa","Performed the altered Anima Invocation and entered Dahak's demiplane; Defeated the Manifestation of Dahak",4720,5,5)
]