import { Event } from "../events.js";

export const AGEOFASHES = [
    new Event("aoa","Breachill hosted the <i>Call to Heroes</i>, ultimately recruiting the party to investigate Hellknight Hill",4719,9,22),
    new Event("aoa","Met Benjemyn Trayle; discovered a circle of <i>aiudara</i> below the abandoned citadel - Alseta's Ring",4719,9,24),
    new Event("aoa","Travelled through Huntergate and survived the vision of Dahak trapped within the <i>aiudara</i>; Met the Ekujae on the other side; Ben was disqualified from a dancing competition",4719,10,15),
    new Event("aoa","Attended the Akrivel Welcome Feast; Nketiah told them the story of the Great Darkness and the <i>anima invocation</i> ritual the elves had used to trap it",4719,10,16),
    new Event("aoa","Met Gerhard Pendergrast and learned that he was seeking an ancient elven temple in order to destroy it and prevent people from discrediting his academic claims",4719,10,26),
    new Event("aoa","They were unable to stop Gerhard Pendergrast from setting off his explosives and exploding the Ancient Temple; Gerhard Pendergrast died in the blast, while the rubble fell around a stunned Grannok",4719,10,29),
    new Event("aoa","The kobold cultist, Hezle, asked them to kill the vrock guarding the camp; The party defeated everything at the Cinderclaw Mine; Despite Hezle offering them use of her shack, Ben slept outside and got malaria",4719,11,11),
    new Event("aoa","The party defeated all the cultists at the Fortress of Sorrow; Ardbert nearly died to a door; With the help of the captured red dragon, Kyrion, they defeated the Cinderclaws leader, Belmazog",4719,11,22),
    new Event("aoa","Destroyed the Vision of Dahak; Returned to Breachill",4719,12,1),
    new Event("aoa","Dr Bang was kidnapped by the Scarlet Triad; The party nearly burned down his shop in their rescue attempt",4719,12,8),
    new Event("aoa","Travelled through Dreamgate",4719,12,9),
    new Event("aoa","Stopped slavers at Cypress Point; Grannok was humbled in a one-on-one fight with One-Eye Ammin; Halleka Shadeborn agrees to pay for their travel to Kintargo",4719,12,10),
    new Event("aoa","The party learned of threats to the Bellflower Network and agreed to warn the members; Mialari Docur was already aware, and they arrived to the Longs Road Coffeehouse too late to stop an attack; Ardbert was magicked into leaving the coffeehouse to seek help from the guards",4719,12,13),
    new Event("aoa","Assaulted Summershade Granite Quarry; Ben was blinded by the lich, Jaggaki",4719,12,14),
    new Event("aoa","Halleka restored Ben's sight; The party returned to the Quarry and freed the slaves; Laslunn was defeated; From her correspondence, the party learned of a mysterious Benefactor and a Scarlet Triad member called Ilssrah Embermead stationed under the mountains",4719,12,17),
    new Event("aoa","Travelled through Jewelgate",4720,1,2),
    new Event("aoa","The party travelled through Saggorak to the city of Kovlar, where they met with the Council of Regents",4720,1,3),
    new Event("aoa","Grannok was arrested by Chiselrock's corrupt guards; Grannok broke himself out of jail to assist the others when they came to rescue him, only for the entire group to end up imprisoned; Ben uses magic to escape and organises a successful prison break with Dr Bang and Commander Hammersong",4720,1,4),
    new Event("aoa","Freed Triad slaves from the Hidden Forge; Met with the ghost king of Saggorak, King Harral, who asked them to retrieve his crown from the hoard of the magma dragon, Veshumirix",4720,1,6),
    new Event("aoa","Grannok attempted to challenge Ilssrah Embermead to a one-on-one fight, but the rest of the group disagreed and joined the battle",4720,1,9),
    new Event("aoa","Descended into the volacno and defeated Veshumirix; Returned King Harral's crown",4720,1,10),
    new Event("aoa","Travelled through Duskgate to the gnome village Finderplain and helped them defeated the wendigo's hunting in the town",4720,1,16),
    new Event("aoa","Arrived in Katapesh; Began planning how to discredit Uri and the Scarlet Triad",4720,1,21),
    new Event("aoa","Ardbert hosted a play for the Bakers Guild and Peshmongers Guild; Dr Bang attempted to sell poisons on the street but had to disappear when the Zephyr Guard appeared; Ben failed to impress the Barristers when they realised he had no credentials",4720,1,25),
    new Event("aoa","Grannok signed up for the qualifying match at the arena; The party successfully beat the solifugid",4720,1,26),
    new Event("aoa","Learned of the slave auction at the Bhetshamtal Estate",4720,1,28),
    new Event("aoa","Ben infiltrated the Barrister's Guild as Lord Bosslesworth",4720,1,29),
    new Event("aoa","Guild Leader Bshez Shak fought the party in the arena and, after her loss, was disavowed from the guild",4720,2,9),
    new Event("aoa","Grannok was elected as the leader of the Katapesh Gladiator Guild",4720,2,12),
    new Event("aoa","Exavisu Kerndallion and other slaves were rescued from the Bhetshamtal Estate",4720,2,14),
    new Event("aoa","The party recovered a prize camel, Duneshadow, from a simurgh; Ardbert attempted to leave the holy bird with some art to commemorate the camel's beauty, but the simurgh was unimpressed",4720,2,16),
    new Event("aoa","Lord Bossleworth was declared dead; Uri and the Scarlet Triad were discredited from the Council of Guilds",4720,2,26),
    new Event("aoa","Ben paid off Dwazo Yelsi's student loans; Ventured into the depth of the Red Pyramid to find Uri Zandivar; Defeated Uri; Ben was petrified and put in the <i>bag of holding</i> while the rest of the party fled from an Adamantine Golem",4720,2,27),
    new Event("aoa","Attempted to open Vengegate and released the Manifestation of Dahak on Breachill; Ben almost died in the demonic flames of a balor's death throes",4720,4,4),
    new Event("aoa","Arrived in Hermea; Met Emaliza and Inizra",4720,4,5),
    new Event("aoa","Dr Bang was ordered by Emaliza to obtain the Shards of Gold Dragonkind",4720,4,6),
    new Event("aoa","Fought Emaliza alongside Mengkare; Convinced the gold dragon to try the altered version of the anima invocation",4720,4,8),
    new Event("aoa","Performed the altered Anima Invocation and entered Dahak's demiplane; Defeated the Manifestation of Dahak",4720,5,5)
]