import { Event } from "../events.js";

export const ABOMINATIONVAULTS = [
    new Event("av","Learned of potential danger in the Fogfens",4721,5,3),
    new Event("av","Travelled to Gauntlight for the first time; Petra was killed",4721,5,4),
    new Event("av","Met Boss Skrawng; Asked to kill the Mushroom-Eyed King on the floor below",4721,5,5),
    new Event("av","Gauntlight's beam caused the dead to rise from their graves",4721,5,10),
    new Event("av","Gorul and Ziskilly were rescued from the morlocks; Shad had been taken further down",4721,5,16),
    new Event("av","Met Zozzlarin; He gave Glodrum his centuries-old memory",4721,5,18),
    new Event("av","Met Augrael; Made a deal with Korlok; Glodrum nearly lost a finger",4721,5,27),
    new Event("av","Aller Rosk took Kahiki, Khesk, and Glodrum into captivity",4721,5,28),
    new Event("av","Spoons recruited Jeigan, Max, and Verity to assist with her rescue mission; Khesk lost an arm; Glodrum lost his index finger",4721,5,29),
    new Event("av","Shad was rescued; Korlok was freed from his contract; Max left for Absalom",4721,6,1),
    new Event("av","Glodrum begins writing 'Twelve Hours Like a Week'",4721,6,2),
    new Event("av","Gauntlight lights again; More dead rise",4721,6,10),
    new Event("av","Met the ghost of Otari; Defeated but didn't kill Volluk; Freed Lasda",4721,6,12),
    new Event("av","Met Hesketh and Fingal; Obtained the Artifacts of the Roseguard",4721,6,13),
    new Event("av","Opened the Barrier to the lower levels of the vaults; Carman Rajani was imprisoned",4721,6,14),
    new Event("av","Finn and Khesk fell into a pit and were killed by hydra",4721,6,15),
    new Event("av","Dorianna's nightmares began; Met Marvin and Eri; Met Chafkhem",4721,6,16),
    new Event("av","Performed at the Warped Brew Tavern; Ran an impromptu heist to rescue the 'food'; Learned of Yldaris from Falxi Orshendiel",4721,6,19),
    new Event("av","Karlthe and Worliwynn are taken; Volluk and Vaulgrist are defeated",4721,6,21),
    new Event("av","Marvin was killed by Jafaki; Jafaki was defeated; Chafkhem left the vault",4721,6,22),
    new Event("av","Spoons and Glodrum identified 'The Motley Man' as a Denizen of Leng; Met Mar-T'an",4721,6,23),
    new Event("av","Defeated the hydras; Recovered the Cooperative Blade",4721,6,24),
    new Event("av","Glodrum made a deal with Urevian and sold both his and Carman Rajani's soul in exchange for Urevian and his devils to leave the vaults; Mar-T'an beat up Carman and put him in a potato sack; Ysondkhelir was killed and Dorianna was freed; Mar-T'an sold his soul to Szek for 250 years in exchange for a bit of luck",4721,6,25),
    new Event("av","Belcorra attacked the party for the first time",4721,6,28),
    new Event("av","Traded with some chuul for their eggs; Formed an alliance with Dulac and the Cult of Urthagul; Belcorra attacked again, leaving Dulac and Padli the only surviving members of the Cult",4721,6,29),
    new Event("av","Belcorra feebleminded Spoons, leaving her <i>stupefied 4</i>; Descended to Yldaris to meet and ally with the drow; Learned of the Fulcrum Lenses and the power of the Empty Death",4721,7,1),
    new Event("av","Met the remaining calignis and promised to help them escape the Vaults; Defeated Urthagul and claimed the Crimson Fulcrum Lens", 4721,7,3),
    new Event("av","Assaulted the urdefhan stronghold; defeated Khurfel and claimed the Emerald Fulcrum Lens", 4721,7,4),
    new Event("av","Ventured out onto the Deep Lake; recovered the Ochre Fulcrum Lens after an intense fight with the deepwater dhuthorexes",4721,7,5),
    new Event("av","Defeated the black dragon, Ravirex, who had killed Glodrum's wife; Glodrum recovered his clan dagger; led the calignis out of the vault",4721,7,6),
    new Event("av","Fled from Caliddo Haruvex at Belcorra's Vault",4721,7,7),
    new Event("av","Defeated Caliddo Haruvex; Recovered the Fulcrum Lattice",4721,7,8),
    new Event("av","Entered the ancient Black Doors; Descended to the lowest level of the Vaults; Unknowingly began Nhimbaloth's trials",4721,7,9),
    new Event("av","Completed the trials; Defeated Lady's Whisper; Eri died; Sent Belcorra to the Empty Death; Escaped the Abomination Vaults",4721,7,11),
    new Event("av","Eri was resurrected by a ritual in Absalom",4721,7,14),
    new Event("av","Attended Shad Nunder and Honey Tittensor's Heartbond Ceremony",4721,7,24)
]
