import { Event } from "../events.js";
import { Character } from "../characters.js";

export const AVCHARACTERS = [
    new Character("av","Eri",true,"img/av/eri.png"),
    new Character("av","Finn",false,"img/av/finn.png"),
    new Character("av","Glodrum",true,"img/av/glodrum.png"),
    new Character("av","Jeigen",true,"img/av/jeigen.png"),
    new Character("av","Kahiki",true,"img/av/kahiki.png"),
    new Character("av","Khesk",false,"img/av/khesk.png"),
    new Character("av","Mar-T'an",true,"img/av/mar tan.png"),
    new Character("av","Marvin",false,"img/av/marvin.png"),
    new Character("av","Max",true,"img/av/max.png"),
    new Character("av","Petra",false,"img/av/petra.png"),
    new Character("av","Spoons",true,"img/av/spoons.png"),
    new Character("av","Verity",true,"img/av/verity.png")
]

export const ABOMINATIONVAULTS = [
    new Event("av","Founder's Day in Otari; Learned of potential danger in the Fogfens from Wrinn",4721,5,3),
    new Event("av","Travelled to Gauntlight for the first time; Glodrum wass tricked by the mitflits into eating their excrement; Petra was killed",4721,5,4),
    new Event("av","Met Boss Skrawng and his pet, Bite-Bite; Boss Skrawng asked them to kill the Mushroom-Eyed King on the floor below; ",4721,5,5),
    new Event("av","Met the brownie, Tangletop; learned of Belcorra's apprentice, Volluk; discovered that Shad Nunder and his friends had gone missing at the ruins a week earlier",4721,5,9),
    new Event("av","Gauntlight's beam caused the dead to rise from their graves",4721,5,10),
    new Event("av","Mayor Oseph Menhemes asked the party to investigate the light and stop it from shining again",4721,5,11),
    new Event("av","Found the morlocks on the first level down, as well as the corpse of Wesker Jesp",4721,5,13),
    new Event("av","Gorul and Ziskilly were rescued from the morlocks; Shad had been taken further down",4721,5,16),
    new Event("av","Met the cleaner, Zozzlarin; He gave Glodrum his centuries-old memory and asked the party to return his contract to him; Recovered the soul gem of Borbo, Volluk's servant, and released his soul to the Boneyard",4721,5,18),
    new Event("av","Made a deal with the devil, Korlok, to be allowed to roam the floor as long as they only return once they had his contract; Glodrum nearly lost a finger when a group of ghouls demanded flesh in return for safe passage",4721,5,27),
    new Event("av","Aller Rosk took Kahiki, Khesk, and Glodrum into captivity; Spoons escaped back to Otari",4721,5,28),
    new Event("av","Spoons recruited Jeigan, Max Nunder, and Verity to assist with her rescue mission; Khesk lost an arm; Glodrum lost his index finger",4721,5,29),
    new Event("av","Met the ghost of Volluk's lover, Chandriu, and learned that she believes Volluk is still alive but has abandoned her",4721,5,31),
    new Event("av","Shad was rescued; Korlok was freed from his contract; Max left for Absalom",4721,6,1),
    new Event("av","Glodrum began writing 'Twelve Hours Like a Week'; the leader of the ghouls told them that Belcorra was coming back",4721,6,2),
    new Event("av","Gauntlight lit up again; More dead rose but were quickly dealt with; Attempted to turn Chandriu from Volluk but ultimately ended up fighting her; Jaul Mezmin surrendered to them and was imprisoned in Otari",4721,6,10),
    new Event("av","Glodrum convinced Carman to give him a 'Buy 30, Get 1 Free' loyalty card for shields",4721,6,11),
    new Event("av","Met the ghost of Otari, who told them that he could feel Belcorra as a ghost far below; Defeated but didn't kill Volluk; Freed Lasda",4721,6,12),
    new Event("av","Met Fingal and his aunt, Hesketh; Learned of Shad and Honey Tittensor's engagement; Obtained the Artifacts of the Roseguard",4721,6,13),
    new Event("av","Opened the Barrier to the lower levels of the vaults; Otari was pulled down to the lower levels; Carman Rajani was imprisoned",4721,6,14),
    new Event("av","Finn and Khesk fell into a pit and were killed by hydra",4721,6,15),
    new Event("av","Dorianna's nightmares began; Marvin and Eri joined the party; Met the administrator of the Gauntlight Arena, Chafkhem",4721,6,16),
    new Event("av","Performed at the Warped Brew Tavern; Ran an impromptu heist to rescue the 'food'; Learned of Yldaris from Falxi Orshendiel",4721,6,19),
    new Event("av","Karlthe and Worliwynn are taken; Volluk and Vaulgrist are defeated; Glodrum ripped the head off Dorianna's toy griffon in front of her",4721,6,21),
    new Event("av","Jafaki was defeated, but Marvin was killed in the battle; Chafkhem left the vault",4721,6,22),
    new Event("av","Spoons and Glodrum identified 'The Motley Man' as a Denizen of Leng; Met Mar-T'an",4721,6,23),
    new Event("av","Defeated the hydras; Recovered the <i>Cooperative Blade</i>",4721,6,24),
    new Event("av","Glodrum made a deal with Urevian and sold both his and Carman Rajani's soul in exchange for the location of 'The Motley Man' and for Urevian and his devils to leave the vaults; Mar-T'an beat up Carman and put him in a potato sack; Ysondkhelir was killed and Dorianna was freed; Mar-T'an sold his soul to Szek for 250 years in exchange for a bit of luck",4721,6,25),
    new Event("av","Belcorra attacked the party for the first time, ordering them to leave her Vault; Interrupted a meditation and accidentally incited a chain reaction of Caligni explosions; Met the urdefhan prisoner, Huglu, and learned of War Chief Khurfel",4721,6,28),
    new Event("av","Traded with some chuul for their eggs; Formed an alliance with Dulac and the Cult of Urthagul; Belcorra attacked again, leaving Dulac and Padli the only surviving members of the Cult",4721,6,29),
    new Event("av","Belcorra feebleminded Spoons, leaving her <i>stupefied 4</i>; Descended to Yldaris to meet and ally with the drow; Learned of the Fulcrum Lenses and the power of the Empty Death from Quorra Orshendiel",4721,7,1),
    new Event("av","Met the remaining calignis and promised to help them escape the Vaults; Defeated Urthagul and claimed the Crimson Fulcrum Lens", 4721,7,3),
    new Event("av","Assaulted the urdefhan stronghold; defeated Khurfel and claimed the Emerald Fulcrum Lens", 4721,7,4),
    new Event("av","Ventured out onto the Deep Lake; recovered the Ochre Fulcrum Lens after an intense fight with the deepwater dhuthorexes",4721,7,5),
    new Event("av","Defeated the black dragon, Ravirex, who had killed Glodrum's wife; Glodrum recovered his clan dagger; Led the calignis out of the vault",4721,7,6),
    new Event("av","Fled from Caliddo Haruvex at Belcorra's Vault",4721,7,7),
    new Event("av","Defeated Caliddo Haruvex; Recovered the Fulcrum Lattice and learned that uniting the four lenses would draw Nhimbaloth's deadly gaze",4721,7,8),
    new Event("av","Entered the ancient Black Doors; Descended to the lowest level of the Vaults; Unknowingly began Nhimbaloth's trials",4721,7,9),
    new Event("av","Completed the trials; Defeated Lady's Whisper; Eri died in the battle against Belcorra; Infused Belcorra with the power of all four lenses and Nhimbaloth dragged her to the Empty Death; Escaped the collapsing Abomination Vaults",4721,7,11),
    new Event("av","Eri was resurrected by a ritual in Absalom",4721,7,14),
    new Event("av","Attended Shad Nunder and Honey Tittensor's Heartbond Ceremony",4721,7,24)
]
