import { Event } from "../events.js";

export const BLOODLORDS = [
    new Event("bl","Met with Berline Haldoli at her manor in Graydirge; Investigated the situation at Old Ergagh's Farm",4722,7,27),
    new Event("bl","Finished restoring the farm; Granted the key's to Qhallaqh's Manor by Berline",4722,7,29),
    new Event("bl","Arrived at Qhallaqh Manor; Met Arghun the Annihilator; Began the clear-out of the basement",4722,7,30),
    new Event("bl", "Met with Ortagar Stitch-Skull at the Empty Threshold",4722,8,7),
    new Event("bl","Investigated the Bone Shards Hideout; Talus was lost amid collapsing bones; Learned of Kepgeda the Hag-Nailed and her interest in the bank; Investigated the abandoned Greydirge Bank",4722,8,8),
    new Event("bl","Assaulted the Crooked Coffin Brewery seeking Kepgeda; Defeated Kepgeda and learned of the Graveclaw Coven",4722,8,10),
    new Event("bl","Dined with Taf-Gekhta Seven-Stomachs; Revealed the true ownership of the Graydirge to the Tax Collectors Guild",4722,8,13),
    new Event("bl","Berline told them of Iron Taviah's connection to the Graveclaw and asked them to travel to the Axan Wood and kill the hag",4722,8,22),
    new Event("bl","Began searching the Axan Wood; Met the huldra, Drusilla, and correctly answered her riddles",4722,8,25),
    new Event("bl","Met Ginness' neglected half-brother, Nebumi, in Iron Taviah's attic; Defeated Iron Taviah; Iron Taviah's Cottage absorbed her body and attempted to digest the party; Siegmeyer was killed",4722,8,26),
    new Event("bl","Arrived in Sallowshore; Met with Tobias Highridge and agreed to retrieve his late wife's Heartstone; Highridge demanded his junior associate, Xanthos, accompany them",4722,9,3),
    new Event("bl","Opened the Builder's League Vault; Returned the Potion of Annulment to Stana Keystone",4722,9,5),
    new Event("bl","Descended to the sunken Temple of Urgathoa; The meat guardians demanded they destroy Sahni's shrine to Dagon; Defeated Sahni Bride-of-the-Sea; Xanthos was cursed with hooves, Ginness with lost time; Destroyed the Shrine to Dagon; Returned Nepenthe's body to Tobias; Xanthos was instructed to go with the others",4722,9,6),
    new Event("bl","Chartered a ship north towards Yled",4722,9,7),
    new Event("bl","Arrived in Yled; Curses removed",4722,9,19),
    new Event("bl","Organised transport to Pagked; Met Bask Vishky",4722,9,20),
    new Event("bl","Arrived in Pagked; Started the search for Decrosia; Bask made a deal with The Shroud; Nebumi began the return trip to Yled alone",4722,9,23),
    new Event("bl","Infiltrated Decrosia's factory; Killed Decrosia and escaped Pagked",4722,9,25),
    new Event("bl","Arrived back in Yled; Bask was fired by Mauldor Gavvik; Were introduced to Blood Lord Zthni and Blood Lord Kyril Vonth by Berline; Spent the entire night indulging with Zthni",4722,10,4),
    new Event("bl","Attended Nathnelma's lecture, <i>Creating Unusual Undead</i>",4722,10,5),
    new Event("bl","Played board games with Blood Lord Kyril Vonth; Bask and Xanthos were caught in a Pharasmin attack at the Pallidium; Ginness, Shade, and Kiya investigated Nathnelma's Office; They learned of Nathnelma's likely involvement in the Graveclaw and her interest in Shadow Ash",4722,10,6),
    new Event("bl","Learned of the Graveclaw's mysterious patron; Ambushed and captured Nathnelma; Shade was killed by <i>Cloudkill</i>",4722,10,7),
    new Event("bl","Ginness starts having nightmares",4722,10,22),
    new Event("bl","Ginness' nightmares end'",4722,10,30),
    new Event("bl","Shade's mummification was completed",4722,11,4),
    new Event("bl","Contacted by Seldeg Bhedlis and asked to join him as he follows the newly-risen Iron Taviah's trail",4722,11,19),
    new Event("bl","Arrived at Iron Taviah's Shadow Cottage; Retreated from a young umbral dragon that had claimed the ground floor as their lair",4722,11,21),
    new Event("bl","Defeated the umbral dragon with Seldeg's help; Destroyed the heart of the Shadow Cottage; Found evidence that Iron Taviah was travelling to Thornhearth",4722,11,22),
    new Event("bl","Arrived to Thornhearth; Learned of Kiya's connection to the Benefactor and of the Benefactor's fate; Put Leysa, Kiya's mother, in place as the new Benefactor; Identified Hollow Flesh as Iron Taviah's next destination",4722,11,29),
    new Event("bl","Arrived at Hollow Flesh Market; Discovered Iron Taviah had returned as a Vetalarana Vampire and was heading south to the Field of Maidens",4722,12,2),
    new Event("bl","Set up camp in the Field of Maidens; Seldeg returned to Mechitar and left the party in charge of investigating Iron Taviah",4722,12,7),
    new Event("bl","Encountered Kerinza, the 'Lonely Maiden' among the stone statues; discovered a military camp on the ridge led by The Rhino",4722,12,8),
    new Event("bl","Discovered another Holoma camp in the Field of Maidens, this time the personal retinue of Lasheeli Aminda of Zuntisha",4722,12,10),
    new Event("bl","Met with the ghoul smuggler Yulthruk, who they agreed to leave alone, and retrieved the Zuntishan supplies from him",4722,12,12),
    new Event("bl","Gained the Rhino's trust and learned of her true purpose in Geb - to unite Nwanyi with a foreign war; Persuaded the Rhino that her plans were foolish and convinced her to leave the Field of Maidens",4722,12,18),
    new Event("bl","Delivered the Nwanyian equipment to the Zuntishans; Led Lasheeli to the statues of her family",4722,12,20),
    new Event("bl","Met with Kerinza at her home and learned that Iron Taviah had travelled to Gristlehall; Destroyed Iron Taviah; Fought with Kerinza, leading to the petrification of Bask, Ginness, and Xanthos; Kiya made a deal with Kerinza to restore two of them in exchange for all their magical items, but betrayed her after Xanthos' restoration",4722,12,21),
    new Event("bl","Seldeg confirmed Chancellor Kemnebi's involvement in the poisoning plot, but warned them he was too powerful to accuse without hard evidence; The group was told to make their way to Mechitar for a meeting with Geb himself, should they choose to continue investigating",4722,12,22),
    new Event("bl","Attended an audience with Geb, where he named the party as the newest Blood Lords; Assigned as Kortash Khain's honour guards along with recent Blood Lord Nohi Tisras",4723,2,2),
    new Event("bl","The Blood Lords, except Nohi, officially moved into their state-granted Alcazar; Met with Harmony in Agony, Weeping Jack, and Rumin; Kortash Khain told them of a fanatical Kabriri cult based in Mechitar",4723,2,3),
    new Event("bl","Ginness asks Kortash Khain to give her ghoul fever and agrees to respect Kabriri in return",4723,2,7),
    new Event("bl","After a few days of fever, Ginness dies; Before she passes, Xanthos gives her a rose in a chicken",4723,2,11),
    new Event("bl","Ginness rises as a ghoul; Berline visits the alcazar to join the celebration and remind them of her role in their rise to power",4723,2,12),
    new Event("bl","The Blood Lords began their assault on Nodbones; the grave demon Ragrathax was defeated; Yurgak and Vaock offered knowledge and magic in exchange for their escape, but the Blood Lords chose to kill them",4723,2,14),
    new Event("bl","Exchequer Kyril Vonth organises a weekly games night with the Blood Lords while he is in Mechitar",4723,2,15),
    new Event("bl","Ginness receives a letter from Jaromir's lawyer informing her that their marriage contract has been voided",4723,3,9),
    new Event("bl","Although Kortash is unimpressed by the motivation behind Xanthos' undeath, he gifts the Blood Lords two rituals as he no longer considers them fools",4723,4,2),
    new Event("bl","After accompanying Kortash on a tour of the harbour, the Blood Lords see a commotion on the <i>Wyvern's Wife</i>; After dealing with several wraiths, they chase down the single fleeing wraith to stop it before it hurts more civilians or find out where it's going",4723,4,15)
]