import { Event } from "../events.js";

export const BLOODLORDS = [
    new Event("bl","Met with Berline Haldoli at her manor in Graydirge; Investigated the situation at Old Ergagh's Farm",4722,7,27),
    new Event("bl","Finished restoring the farm; Granted the key's to Qhallaqh's Manor by Berline",4722,7,29),
    new Event("bl","Arrived at Qhallaqh Manor; Met Arghun the Annihilator; Began the clear-out of the basement",4722,7,30),
    new Event("bl", "Met with Ortagar Stitch-Skull at the Empty Threshold",4722,8,7),
    new Event("bl","Investigated the Bone Shards Hideout; Talus was lost amid collapsing bones; Learned of Kepgeda the Hag-Nailed and her interest in the bank; Investigated the abandoned Greydirge Bank",4722,8,8),
    new Event("bl","Assaulted the Crooked Coffin Brewery seeking Kepgeda; Defeated Kepgeda and learned of the Graveclaw Coven",4722,8,10),
    new Event("bl","Dined with Taf-Gekhta Seven-Stomachs; Revealed the true ownership of the Graydirge to the Tax Collectors Guild",4722,8,13),
    new Event("bl","Berline told them of Iron Taviah's connection to the Graveclaw and asked them to travel to the Axan Wood and kill the hag",4722,8,22),
    new Event("bl","Began searching the Axan Wood; Met the huldra, Drusilla, and correctly answered her riddles",4722,8,25),
    new Event("bl","Met Ginness' neglected half-brother, Nebumi, in Iron Taviah's attic; Defeated Iron Taviah; Iron Taviah's Cottage absorbed her body and attempted to digest the party; Siegmeyer was killed",4722,8,26),
    new Event("bl","Arrived in Sallowshore; Met with Tobias Highridge and agreed to retrieve his late wife's Heartstone; Highridge demanded his junior associate, Xanthos, accompany them",4722,9,3),
    new Event("bl","Opened the Builder's League Vault; Returned the Potion of Annulment to Stana Keystone",4722,9,5),
    new Event("bl","Descended to the sunken Temple of Urgathoa; The meat guardians demanded they destroy Sahni's shrine to Dagon; Defeated Sahni Bride-of-the-Sea; Xanthos was cursed with hooves, Ginness with lost time; Destroyed the Shrine to Dagon; Returned Nepenthe's body to Tobias; Xanthos was instructed to go with the others",4722,9,6),
    new Event("bl","Chartered a ship north towards Yled",4722,9,7),
    new Event("bl","Arrived in Yled; Curses removed",4722,9,19),
    new Event("bl","Organised transport to Pagked; Met Bask Vishky",4722,9,20),
    new Event("bl","Arrived in Pagked; Started the search for Decrosia; Bask made a deal with The Shroud; Nebumi began the return trip to Yled alone",4722,9,23),
    new Event("bl","Infiltrated Decrosia's factory; Killed Decrosia and escaped Pagked",4722,9,25),
    new Event("bl","Arrived back in Yled; Bask was fired by Mauldor Gavvik; Were introduced to Blood Lord Zthni and Blood Lord Kyril Vonth by Berline; Spent the entire night indulging with Zthni",4722,10,4),
    new Event("bl","Attended Nathnelma's lecture, <i>Creating Unusual Undead</i>",4722,10,5),
    new Event("bl","Played board games with Blood Lord Kyril Vonth; Bask and Xanthos were caught in a Pharasmin attack at the Pallidium; Ginness, Shade, and Kiya investigated Nathnelma's Office; They learned of Nathnelma's likely involvement in the Graveclaw and her interest in Shadow Ash",4722,10,6),
    new Event("bl","Learned of the Graveclaw's mysterious patron; Ambushed and captured Nathnelma; Shade was killed by <i>Cloudkill</i>",4722,10,7),
    new Event("bl","Ginness started having nightmares",4722,10,22),
    new Event("bl","Ginness' nightmares ended'",4722,10,30),
    new Event("bl","Shade's mummification was completed",4722,11,4),
    new Event("bl","Contacted by Seldeg Bhedlis and asked to join him as he follows the newly-risen Iron Taviah's trail",4722,11,19),
    new Event("bl","Arrived at Iron Taviah's Shadow Cottage; Retreated from a young umbral dragon that had claimed the ground floor as their lair",4722,11,21),
    new Event("bl","Defeated the umbral dragon with Seldeg's help; Destroyed the heart of the Shadow Cottage; Found evidence that Iron Taviah was travelling to Thornhearth",4722,11,22),
    new Event("bl","Arrived to Thornhearth; Learned of Kiya's connection to the Benefactor and of the Benefactor's fate; Put Leysa, Kiya's mother, in place as the new Benefactor; Identified Hollow Flesh as Iron Taviah's next destination",4722,11,29),
    new Event("bl","Arrived at Hollow Flesh Market; Discovered Iron Taviah had returned as a Vetalarana Vampire and was heading south to the Field of Maidens",4722,12,2),
    new Event("bl","Set up camp in the Field of Maidens; Seldeg returned to Mechitar and left the party in charge of investigating Iron Taviah",4722,12,7),
    new Event("bl","Encountered Kerinza, the 'Lonely Maiden' among the stone statues; discovered a military camp on the ridge led by The Rhino",4722,12,8),
    new Event("bl","Discovered another Holoma camp in the Field of Maidens, this time the personal retinue of Lasheeli Aminda of Zuntisha",4722,12,10),
    new Event("bl","Met with the ghoul smuggler Yulthruk, who they agreed to leave alone, and retrieved the Zuntishan supplies from him",4722,12,12),
    new Event("bl","Gained the Rhino's trust and learned of her true purpose in Geb - to unite Nwanyi with a foreign war; Persuaded the Rhino that her plans were foolish and convinced her to leave the Field of Maidens",4722,12,18),
    new Event("bl","Delivered the Nwanyian equipment to the Zuntishans; Led Lasheeli to the statues of her family",4722,12,20),
    new Event("bl","Met with Kerinza at her home and learned that Iron Taviah had travelled to Gristlehall; Destroyed Iron Taviah; Fought with Kerinza, leading to the petrification of Bask, Ginness, and Xanthos; Kiya made a deal with Kerinza to restore two of them in exchange for all their magical items, but betrayed her after Xanthos' restoration",4722,12,21),
    new Event("bl","Seldeg confirmed Chancellor Kemnebi's involvement in the poisoning plot, but warned them he was too powerful to accuse without hard evidence; The group was told to make their way to Mechitar for a meeting with Geb himself, should they choose to continue investigating",4722,12,22),
    new Event("bl","Attended an audience with Geb, where he named the party as the newest Blood Lords; Assigned as Kortash Khain's honour guards along with recent Blood Lord Nohi Tisras",4723,2,2),
    new Event("bl","The Blood Lords, except Nohi, officially moved into their state-granted Alcazar; Met with Harmony in Agony, Weeping Jack, and Rumin; Kortash Khain told them of a fanatical Kabriri cult based in Mechitar",4723,2,3),
    new Event("bl","Ginness asked Kortash Khain to give her ghoul fever and agreed to respect Kabriri in return",4723,2,7),
    new Event("bl","After a few days of fever, Ginness died; Before she passed, Xanthos gave her a rose in a chicken",4723,2,11),
    new Event("bl","Ginness rose as a ghoul; Berline visited the alcazar to join the celebration and remind them of her role in their rise to power",4723,2,12),
    new Event("bl","The Blood Lords began their assault on Nodbones; the grave demon Ragrathax was defeated; Yurgak and Vaock offered knowledge and magic in exchange for their escape, but the Blood Lords chose to kill them",4723,2,14),
    new Event("bl","Exchequer Kyril Vonth organised a weekly games night with the Blood Lords while he is in Mechitar",4723,2,15),
    new Event("bl","Ginness received a letter from Jaromir's lawyer informing her that their marriage contract has been voided",4723,3,9),
    new Event("bl","Although Kortash was unimpressed by the motivation behind Xanthos' undeath, he gifted the Blood Lords two rituals as he no longer considered them fools",4723,4,2),
    new Event("bl","After accompanying Kortash on a tour of the harbour, the Blood Lords saw a commotion on the <i>Wyvern's Wife</i>; They chased down the single remaining wraith to the Cerulean Glade, where they defeated Rumin Purgo and recovered several samples of <i>Shadow Ash</i>",4723,4,15),
    new Event("bl","Spoke with the harbormaster, Vernetta, and learned the poison was a combination of braingrit, shadow ash, and tremor paste",4723,4,16),
    new Event("bl","Kyril Vonth told the Blood Lords that, although he imagined there was a mistake, games night was cancelled and he was returning to oversee a financial investment in Yled",4723,4,17),
    new Event("bl","The Blood Lords' research led them to Professor Bremeteria Veng at the university as a source of knowledge about <i>Shadow Ash</i>",4723,4,21),
    new Event("bl","Professor Veng told Xanthos that <i>Shadow Ash</i> was initially created by the Empty Chorus, but gaining access to their abandoned Sanctum would require permission from the Cathedral of Epiphenomena",4723,4,28),
    new Event("bl","Both Seldeg and Zthni refused to petition for their entry to the Cathedral; The Blood Lords gave the Export Guild the evidence of Pharasmin presence within the Carters Consortium in exchange for their petition",4723,4,29),
    new Event("bl","Received permission to enter the Yearning Sanctum; Discovered Hyrune's lackeys within the Sanctum; Rinnella Brenon, ruler of the cathedral, suggested they challenge Hyrune to a fight at the Deathless Arena and told them she would provide her own bodyguard as Hyrune's champion to ensure the outcome",4723,5,3),
    new Event("bl","Successfully challenged Blood Lord Hyrune to a match in the Deathless Arena",4723,5,4),
    new Event("bl","Embarassed Hyrune in the arena; Geb stripped Hyrune of his Blood Lord privileges and told the party the location of Hyrune's secret sanctum",4723,5,5),
    new Event("bl","The Blood Lords descended below their alcazar to the Hanging Castle; Hyrune told them of Kemnebi's plans and his anger at Geb; Hyrune was destroyed",4723,5,6),
    new Event("bl","Departed Mechitar and began the journey north to Yled",4723,5,9),
    new Event("bl","Met with Seldeg outside of Yled; Learned of the Warmaster Council and of rumours that the High Priest Pesabnet is involved in smuggling",4723,5,11),
    new Event("bl","Learned that Pokmit Bloody-Pike was making plans to move against Pesabnet",4723,5,14),
    new Event("bl","Pokmit Bloody-Pike took Pesabnet into custody; The Blood Lords examined Pesabnet's things and found leads pointing to the involvement of the theatre owner, Ghiasi the Unraveller",4723,5,15),
    new Event("bl","Ginness asked her ex-husband, Jarek, to provide them tickets to Ghiasi's upcoming show, <i>The Winnowing of Gachanta</i>",4723,5,16),
    new Event("bl","All but Nohi performed in Ghiasi's play as emergency understudies; Followed Ghiasi though a portal to Shadow Yled, where they fought their way to her; After proving their combat prowess, Ghiasi deemed them powerful enough to help and revealed her involvment with Kemnebi",4723,5,17),
    new Event("bl","Xanthos took Ghiasi's place at her scheduled meeting with Kemnebi's in-between; Graelar told them that mass quantities of <i>shadow ash</i> were being produced by the Agorron and led them to its entrance; received evidence of Kemnebi's plots from The Bound One",4723,5,18),
    new Event("bl","Presented the evidence to Geb; Were tasked with receiving Balji's soul from the Boneyard",4723,5,21),
    new Event("bl","Descended into the abandoned Carters Stronghold and met the shabti's still living below; Convinced Erthrais that they would take her to freedom and lied that they wouldn't kill the others",4723,5,27),
    new Event("bl","After failing to deceive Erthrais, she killed herself instead of helping them pass to the Boneyard; Requested Berline's help to open the Passage Pane",4723,5,28),
    new Event("bl","Travelled to the Boneyard and made a deal with Matron Uldrula for Balji's soul urn; Defeated the Arbiter in a close fight on their way out",4723,5,31),
    new Event("bl","Returned Balji's soul urn to Geb",4723,6,2),
    new Event("bl","Geb ordered them to fetch the components he needs for a ritual to restore Balji's soul urn, as well as asking them to retrieve additional components to allow him to untether himself from his throne room; Worked with Seldeg to obtain the armour of Corporal Elgrai instead of Seldeg's own'",4723,6,6),
    new Event("bl","Retrieved cursed shadow from Kulun's Folly",4723,6,7)
]