import { Event } from "../events.js";

export const OUTLAWSOFALKENSTAR = [
    new Event("ooa","Hired by Foebe Dunsmith for a bank heist",4722,4,27),
    new Event("ooa","Stole the lockbox from the Gold Tank Reserve; Met Lord Glass and the Nailgobblers",4722,4,28),
    new Event("ooa","Given a new mission to retrieve Varshon Gattlebee and bring him to the saloon",4722,4,30),
    new Event("ooa","Escorted Gattlebee and his pet chameleon, Slick, to the Yeast of All Brewery",4722,5,4),
    new Event("ooa","Ambushed by Dewey Daystar and his pet drake, Roxy; Gruzwil was killed",4722,5,5),
    new Event("ooa","Introduced to Yin; Began investigating the Powderkeg Punks; Tried to determine if Vix the Bartender was being exploited",4722,5,6),
    new Event("ooa","Visited Ryka's Reagents; Learned the name Lyzerius",4722,5,7),
    new Event("ooa","Astra, Yin, and Yohziah entered the weekly rodeo; Yin won a membership to the Longhorn Lounge; Bribed Bert to gain access to the members list; Mugged a Punk for the password to the Old Widgetworks Warehouse; Met with Glaz Nixbrix and killed his pet snake, Bitey, in exchange for information",4722,5,8),
    new Event("ooa","Found Shoma Lyzerius in Hellside; returned him to the Barrel & Bullet Saloon; Learned that the formula for Pyronite might have been discovered by another.",4722,5,9),
    new Event("ooa","Began investigating Olomann Kosowana; Spent the night in the Asynchronous Archives doing research",4722,5,20),
    new Event("ooa","Chartered a flight into the Spellscar Desert; Gathered a collection of interesting passengers to help fund the trip",4722,5,22),
    new Event("ooa","Began the journey east on the <i>Second Kiss</i>; Ex-shieldmarshal Solessa died during a Peryton attack; Discovered their door had been rigged with a blackpowder bomb; Learned that Usuvu was also seeking Kosowana; Learned Mugland was funding the Gilded Gunners",4722,5,23),
    new Event("ooa","A Chimeric Manticore attacked the Second Kiss; Gbemisola summoned an elephant, which dealt the final blow to the Manticore and fell off the side; The Second Kiss landed in the Spellscar Desert; The party began the walk to the Cradle of Quartz",4722,5,25),
    new Event("ooa","Continued their trek into the Spellscar Desert; Met with a Nyktera colony",4722,5,26),
    new Event("ooa","Arrived at the Cradle of Quartz near midnight; Encountered the Claws of Time; Saved Kosowana",4722,5,27),
    new Event("ooa","Returned to Alkenstar; Learned of the Gilded Gunners plan to steal from the Steaming Kingdom",4722,6,2),
    new Event("ooa","Explosion at the Steaming Kingdom; Found the Gilded Halls and made a deal with Sabora Sharkosa",4722,6,3),
    new Event("ooa","Sabora Sharkosa killed Mugland; Learned of Loveless's plan to sell the formula to two wizards",4722,6,4),
    new Event("ooa","Infiltrated the Vault of Secrets searching for leads on Loveless; Did not escape quietly",4722,6,5),
    new Event("ooa","Attended Christia Tombend's Art Gala; Learned that Christia is seeking support for a bill that would introduce mandatory conscription in Alkenstar",4722,6,6),
    new Event("ooa","Rescued Rhangyl Foruza from execution; Learned that a Nexian wizard, Ibrium, organised the purchase of large quantities of pyronite supplies",4722,6,7),
    new Event("ooa","Met Dash at the Dead Spot outside of Alkenstar; the Headless Rustlers decapitated Yin; learned that Parsus had delivered the materials to the Gunworks",4722,6,8),
    new Event("ooa","Arrived to the Gunworks; Met Tyke Steyrlock; Helped remove gremlins from the Tower of Metallurgy",4722,6,9),
    new Event("ooa","Met with Loy Ayton; The Slugs of the Waste assaulted the Gunworks; The Maw of Rovagug was destroyed by Pyronite; Yohziah was killed by Vewslog, the Cyclops",4722,6,10),
    new Event("ooa","The <i>Gearsmoke</i> Steamboat exploded at the top of Alken Falls, destroying the waterfall and the Tinwound Hydroforge",4722,6,13),
    new Event("ooa","The High Parliament rushed through Tombend's bill of mandatory conscription; Loveless is placed in control of the new standing army",4722,6,17)
]